### ISSUE TITLE
网页监控报错

### ISSUE THREAD

**Issue by irol765** [LogicJake/WebMonitor#52] opened 2021-01-30 04:28 UTC
### 目标网站地址
https://sms-activate.ru/stubs/handler_api.php?api_key=3c98B07cdee5e8B556650e21401ef752&action=getNumbersStatus&country=62

### xpath 内容
/html/body

### 需求
需要抓取"nf_0": "0"中后面那个0有没有变化，使用正则(?<=\"nf_0": ").+?(?=")，监控规则-increase 3

### 部署相关信息
docker

### 额外信息（日志、报错等）
2021-01-30 12:23:49,415 [ThreadPoolExecutor-0_2:139800354998016] [scheduler:monitor:183] [ERROR]- Traceback (most recent call last):
File "/app/task/utils/scheduler.py", line 128, in monitor
status_code = is_changed(rule, content, last_content)
File "/app/task/utils/rule.py", line 132, in is_changed
if rule_fun(args, content, last_content):
File "/app/task/utils/rule.py", line 27, in parse_increase
last_content = float(last_content)
ValueError: could not convert string to float:

**Comment by LogicJake** [comment] 2021-01-30 04:41
@irol765 这个错误说明提取出来的不是纯数字，所以不能转float

**Comment by irol765** [comment] 2021-01-30 04:56
我改了选择器/html/body/text()
现在提示如下：
2021-01-30 12:52:59,318 [ThreadPoolExecutor-0_6:139800380176128] [scheduler:monitor:183] [ERROR]- Traceback (most recent call last):
File "/app/task/utils/scheduler.py", line 126, in monitor
regular_expression, headers)
File "/app/task/utils/extract_info.py", line 36, in get_content
content = selector_handler.get_by_xpath(url, selector, headers)
File "/app/task/utils/selector/request_selector.py", line 42, in get_by_xpath
raise Exception('无法获取文本信息')
Exception: 无法获取文本信息

**Comment by irol765** [comment] 2021-01-30 07:29
问题解决了，奇怪的是我不加监控条件能正常返回数0，加了就任务失败了

**Comment by if1y** [comment] 2021-01-30 10:14
Seems Duplicate of #42

**Closed** 2021-01-31 08:11 UTC
Labels: help wanted, question, 抓取出错

**Comment by hyyxiaoluo** [comment] 2023-08-22 18:34
> 我改了选择器/html/body/text() 现在提示如下： 2021-01-30 12:52:59,318 [ThreadPoolExecutor-0_6:139800380176128] [scheduler:monitor:183] [ERROR]- Traceback (most recent call last): File "/app/task/utils/scheduler.py", line 126, in monitor regular_expression, headers) File "/app/task/utils/extract_info.py", line 36, in get_content content = selector_handler.get_by_xpath(url, selector, headers) File "/app/task/utils/selector/request_selector.py", line 42, in get_by_xpath raise Exception('无法获取文本信息') Exception: 无法获取文本信息

老哥，我现在遇到的是你这样的报错，获取不到文本信息，这个一般是哪里的问题啊不就是这样的格式么：//*[@id="main"]/blockquote/p/text()
刚看了看日志，是这样的
2023-08-23 02:24:50,700 [ThreadPoolExecutor-0_3:139926595163904] [scheduler:add_job:223] [INFO]- 添加定时任务task_4
2023-08-23 02:24:51,244 [ThreadPoolExecutor-0_8:139926142187264] [scheduler:monitor:195] [ERROR]- Traceback (most recent call last):
File "/app/task/utils/scheduler.py", line 140, in monitor
headers)
File "/app/task/utils/extract_info.py", line 63, in get_content
headers)
File "/app/task/utils/selector/request_selector.py", line 30, in get_by_xpath
result[key] = self.xpath_parse(html, xpath_ext)
File "/app/task/utils/selector/selector.py", line 30, in xpath_parse
raise Exception('无法获取文本信息')
Exception: 无法获取文本信息
